### ISSUE TITLE
First step. Loopback intro

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/api-extended-database#1]
https://github.com/optis/loopback-rest-api - this is the best tutorial that helps me 1 year ago.

Please buzz me before including mongodb database - so i'll generate a new instance for you.

As I want to see your progress - please use this repo and push your progress here. Share with me progress and questions that i can help you with. Don't hesitate to use my help. I willing to start fast and with less stress for you at the beginning. Also will check your git skills.

**Comment by khyati0212** [comment]
Is there any timeline to finish?

**Comment by khyati0212** [comment]
Yeah that is why I asked as I am new to this. I will let you know as soon as I reach to mongo-db.

**Comment by atherdon** [comment]
good. because that section require local install. and i think this is not
good way. a lot of people can stuck, especially if they use mongo at
Windows(there a lot of troubles).


On 12-Mar-2018 at 09:48 PM, Khyati wrote:


Yeah that is why I asked as I am new to this. I will let you know as soon
as I reach to mongo-db.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/api-extended-database/issues/1#issuecomment-372474371>,
or mute the thread

**Comment by atherdon** [comment]
Btw, if you need any help with this task - feel free to ask. You also can move your current progress(code) here, so i'll be able to track you

**Comment by khyati0212** [comment]
oh ok. I will do that today.

**Comment by khyati0212** [comment]
Sorry for not posting that before. I am still new to Git so I didnt knew how to do it.

**Comment by atherdon** [comment]
@khyati0212 it's ok - i figure this out and this was the reason why i ask this. in order to train you :)

**Comment by khyati0212** [comment]
Thank you for understanding as always.

**Comment by khyati0212** [comment]
@atherdon I was just going through a tutorial on Lynda.com regarding this.

**Comment by atherdon** [comment]
you mean git basics? if yes, please read also about **git flow** approach then

**Comment by khyati0212** [comment]
No no.. Loopback API

**Comment by atherdon** [comment]
Ohh, got it. Good choice. But keep noted, that we're using Loopback v.3 - soon it will be a big shift into loopback 4 - but we're not ready for it - at this moment

**Comment by khyati0212** [comment]
oh ok. Tutorial is for loopback 4.

**Comment by atherdon** [comment]
Lol. I'm a wizard :))))

**Comment by khyati0212** [comment]
Yeah. :) now i think I should stick with given tutorial than.

**Comment by khyati0212** [comment]
@atherdon need help. I was doing the loopback tutorial and used to lock my PC most of the time but this time I had to restart it and now when I am tring to access that "reservation" app again it is giving error. How to open it again?

**Comment by atherdon** [comment]
what error and by access you mean start nodejs server, right?

**Comment by khyati0212** [comment]
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: The generator must be run in an empty directory.
    at /usr/local/lib/node_modules/loopback-cli/node_modules/generator-loopback/app/index.js:247:12
    at /usr/local/lib/node_modules/loopback-cli/node_modules/loopback-workspace/common/models/workspace.js:488:11
    at /usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/dao.js:2009:11
    at /usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:396:17
    at done (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:167:19)
    at /usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:40:16
    at /usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:393:21
    at /usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/dao.js:1986:17
    at doNotify (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
    at doNotify (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
    at doNotify (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
    at doNotify (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
    at doNotify (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
    at doNotify (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
    at Function.ObserverMixin._notifyBaseObservers (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/observer.js:122:5)
    at Function.ObserverMixin.notifyObserversOf (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/observer.js:97:8)

**Comment by atherdon** [comment]
i think i got it.
you don't need to run a generator twice.
your loopback instance was created in first time.
you just need to run 
`node server/server.js`
try and tell me if this works

**Comment by khyati0212** [comment]
Not working
Another error

Web server listening at: http://localhost:3000
Browse your REST API at http://localhost:3000/explorer
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open 'db.json'
    at Error (native)

**Comment by atherdon** [comment]
can you upload files from your computer into this repo - it's hard to debug things online.
btw, do you have db.json file?

**Comment by atherdon** [comment]
you can find **upload files** button at the root of the repo and drag-n-drop them

**Comment by khyati0212** [comment]
Finally I uploaded it

**Comment by khyati0212** [comment]
"sudo npm start "

This command helped. Now its running fine. Thank you for help. I was googling the answer but was not able to find so have to ask you.

**Comment by atherdon** [comment]
got it. 
btw, in order to make your life easy, please install raven package. this is a good tool, that will be able to show you what and where things were broken on your code.
basically it's error tracker. i'll show you how to configure it.
and don't forget to push changes on code repository.

**Comment by khyati0212** [comment]
Now i can push changes easily once repository is created. Thank you for help. 
Using "https://github.com/getsentry/raven-python" to install raven.

**Comment by atherdon** [comment]
you need to run `npm install raven` - this is javascript version that we need

**Comment by khyati0212** [comment]
Done

**Comment by atherdon** [comment]
small question - you create a separated repository and upload your code into it?

**Comment by khyati0212** [comment]
Oh ok. Sorry I misunderstood it. I can post code in this one too. 
As I said I am new to github. :|

**Comment by atherdon** [comment]
no prob. working on database document for you and I stuck :)
have a lot of things to share and move


On 16-Mar-2018 at 07:39 PM, Khyati wrote:


Oh ok. Sorry I misunderstood it. I can post code in this one too.
As I said I am new to github. :|

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/api-extended-database/issues/1#issuecomment-373823512>,
or mute the thread

**Comment by khyati0212** [comment]
Ok. Let me if you need any help.

**Comment by atherdon** [comment]
it'll be cool if you'll be able to proof-read my text - plan to publish it
as article. my english is not cool - so any help with it will be
appreciated. but still - i need to organize all data that i has before


On 16-Mar-2018 at 07:47 PM, Khyati wrote:


Ok. Let me if you need any help.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/api-extended-database/issues/1#issuecomment-373825446>,
or mute the thread

**Comment by khyati0212** [comment]
I can try. Do send me once you are done.
