### ISSUE TITLE
Error: Cannot create data source "photos": Cannot find module 'pkgcloud'

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/api-extended-database#10]
https://sentry.io/atherdon/grocery/issues/498497917/

```
Error: Cannot create data source "photos": Cannot find module 'pkgcloud'
  File "/home/khyati/reservations/server/server.js", line 43, in Object.<anonymous>
    boot(app, __dirname, function(err) {
...
(49 additional frame(s) were not displayed)

Error: Cannot create data source "photos": Cannot find module 'pkgcloud'
```

**Comment by khyati0212** [comment]
I am trying to solve this error for whole afternoon but could not find anything and finally i started creating new repository.

**Comment by atherdon** [comment]
push code on this repo and i'll be able to take a look. i assume it's usual for img upload thng - something with folder rights. don't worry and maybe take a break :1st_place_medal:

**Comment by khyati0212** [comment]
Oh. I saw resolution online and it suggested to install npm pkgcloud as well but it didn't work

**Comment by khyati0212** [comment]
I uploaded all the files except node_modules folder. It is giving some error. I will check them after 11 pm. I have my art class right now.

**Comment by atherdon** [comment]
good! will check it right now

**Comment by atherdon** [comment]
i didn't see package files. i think you should upload all files(not node_modules module) at root folder

**Comment by atherdon** [comment]
I'll use my own package.json while you push it. maybe will be able to debug some side-effects :) more comments soon

**Comment by khyati0212** [comment]
I tried uploading all the files again
can you check if they are visible or not?

**Comment by atherdon** [comment]
yes, it works. will create some task related to "make things easier for you with git"

**Comment by atherdon** [comment]
@khyati0212 delete your previous folder. clone an updated code version into a new one.
don't cheat :)

**Comment by atherdon** [comment]
plz close this issue when it'll work on your side too

**Comment by khyati0212** [comment]
It worked.
# Remove node_modules
rm -fr node_modules

# Reinstall packages
npm i

with these commands

**Comment by atherdon** [comment]
so you're cheated?


On 21-Mar-2018 at 12:48 AM, Khyati wrote:


It worked.
Remove node_modules

rm -fr node_modules
Reinstall packages

npm i

with these commands

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/api-extended-database/issues/10#issuecomment-374805589>,
or mute the thread
