### ISSUE TITLE
raven/sentry configuration

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/api-extended-database#4]
`Raven.config('https://77aa2ee9a7ce484497f56278982a0809@sentry.io/305339').install()`

Init:
https://github.com/GroceriStar/groceristar/blob/master/server/server.js#L17

How to use this tracer:
https://github.com/GroceriStar/groceristar/blob/master/server/server.js#L60

if you'll cover your code well with this tracer - when you'll break something - I'll receive an email notification and will be able to understand more clearly what was goes wrong.

![image](https://user-images.githubusercontent.com/1469198/37542679-b443d8f0-2967-11e8-8d98-7fc3e9aabe6b.png)

**Comment by atherdon** [comment]
is this task completed?

**Comment by khyati0212** [comment]
export SENTRY_DSN=https://77aa2ee9a7ce484497f56278982a0809@sentry.io/305339

I did this on bash shell. It will work right?

**Comment by atherdon** [comment]
no, you just need to add first code row into files as at examples...

**Comment by khyati0212** [comment]
Understood raven/sentry finally. Added the configuration to Server.js.
Although haven't added try catch block yet.

**Comment by atherdon** [comment]
good! using it to track your errors is just a good habit, i mean it's just a tool - so i think soon you'll get how to use it. it's also a big thing when you work with backend models, send queries. so soon you'll use them a lot.

**Comment by khyati0212** [comment]
Yeah it seems like it after understanding it.. i understood raven and web application structure fow JS and node.js.. Now working on Mongo n Node..

**Comment by atherdon** [comment]
Got it. do you need my help with Mongo? i mean i can speed up something, or
just wait - as you wish

**Comment by khyati0212** [comment]
If you can help speeding up it would be great. I finished understanding basic syntax of mongo. Now was going to learnt to use it with node js and web app.

**Comment by atherdon** [comment]
to be honest - we use mongo only like storage. i mean there not a lot of
stuff that should be configured outside the loopback.

loopback has a one syntax for most used DBs. so if you learn how queries
works at Loob\pback - then db connection can be anyone(like mysql, ms sql,
nosql, etc)


On 02-Apr-2018 at 06:54 PM, Khyati wrote:


If you can help speeding up it would be great. I finished understanding
basic syntax of mongo. Now was going to learnt to use it with node js and
web app.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/api-extended-database/issues/4#issuecomment-378009947>,
or mute the thread

**Comment by khyati0212** [comment]
Ok let me try. I thought i would need more knowledge.

**Comment by atherdon** [comment]
you'll need a basic knowledge, related to how mongo differentiates from mysql, for example. but some settings thing - you;ll not need right now. because it's for advanced users/situations only. for now it's all similar to mysql - select/insert/find - just names is different

**Comment by khyati0212** [comment]
Ok

**Comment by atherdon** [comment]
and as i want a from the box validation(loopback) - i setup a database at SQL style. with a lot of tables, relations, etc
