### ISSUE TITLE
read about git flow and create a future branch for development process

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/api-extended-database#7]
# Description/Steps to reproduce
https://codeburst.io/trunk-based-development-vs-git-flow-a0212a6cae64 **i'll examine you**. understand the logic of future branching.

https://devcenter.heroku.com/articles/node-best-practices

**Comment by khyati0212** [comment]
created new "futureBranch" haven't changed the code so could not generate pull request.

**Comment by atherdon** [comment]
@khyati0212 you can add some changes at readme file in order to have a practice

**Comment by khyati0212** [comment]
Done. Did some changes into readme file. Worked on futureBranch. Created pull request.

**Comment by atherdon** [comment]
can you create another branch, named develop from futureBranch?

**Comment by khyati0212** [comment]
Done. Created new branch develop from futureBranch.
